### ISSUE TITLE
Duplicate name check behavior doesn't match that of LM indexer

### ISSUE THREAD

**Issue by per1234** [per1234/ino-library-manager-validator#1]
https://github.com/arduino/Arduino/issues/9582#issuecomment-571787976 shows that there is a mismatch in behavior between this project's duplicate library name check and the Library Manager indexer.

https://github.com/ardnew/XPT2046_Calibrated originally had the library.properties `name` value `XPT2046_Touchscreen`:
https://github.com/ardnew/XPT2046_Calibrated/blob/v1.3/library.properties#L1
which is already taken. But the `name` value was later changed to the unique value `XPT2046_Calibrated` in the v1.0.0 tag:
https://github.com/ardnew/XPT2046_Calibrated/blob/v1.0.0/library.properties#L1

This script checked the XPT2046_Calibrated name and passed because it found it unique, but inclusion in the Library Manager index failed because the name was considered to be `XPT2046_Touchscreen`. I would have expected the library name to be based on the `name` value of the chronologically newest tag at the time of the LM inclusion request, but evidently this is not so.

An extra complication in this case is that the newest tag chronologically has `version` value `1.0.0`, while there are previous tags (with the `XPT2046_Touchscreen` name) with `version` values `1.0` through `1.3`.

**Comment by ardnew** [comment]
@per1234 perhaps this issue would resolve itself if I retag the latest release to something following `1.3` such as `1.4.0` ? I felt it appropriate to re-baseline the version number to `1.0.0` since the project name was changed before requesting LM inclusion.

**Comment by cmaglie** [comment]
Don't worry starting from `1.0.0` is fine.

**Comment by per1234** [comment]
I'm closing this issue due to the deprecation of the project in favor of Arduino Lint:
https://arduino.github.io/arduino-lint/latest/#library-manager-setting
